# -*- coding: utf-8 -*-
"""Projekt7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wjbHFe6SeTWbutC8snMwQzv8r3vLw5Q
"""

!pip install google-colab

pip install imutils

import cv2
import imutils
from google.colab.patches import cv2_imshow

img = cv2.imread('monet.jpg')

cv2_imshow(img)
cv2.waitKey(0)

cv2.imwrite('nazwa_pliku.png', img)

cv2_imshow(img[200:400,0:800])

new_size = (640, 480)
resized_img = cv2.resize(img, new_size)

cv2_imshow(resized_img)
cv2.waitKey(0)

(h, w) = img.shape[:2]

# Określenie punktu obrotu - środek obrazu
center = (w // 2, h // 2)

# Macierzy przekształcenia
M = cv2.getRotationMatrix2D(center, 45, 1.0)

# Wykonanie obrotu
rotated = cv2.warpAffine(img, M, (w, h))

cv2_imshow(rotated)
cv2.waitKey(0)

blurred_img = cv2.blur(img, (5, 5))
cv2_imshow(blurred_img)
cv2.waitKey(0)

img2 = cv2.imread('monet2.jpg')

# skalowanie obrazów do takiego samego rozmiaru
img = cv2.resize(img, (500, 500))
img2 = cv2.resize(img2, (500, 500))

# połączenie obrazów wzdłuż osi poziomej
combined_img = cv2.hconcat([img, img2])

cv2_imshow(combined_img)
cv2.waitKey(0)

# umieszczenie tekstu na obrazie
text = 'ZOFIA'
position = (50, 50) # pozycja tekstu (współrzędne pikseli)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
font_scale = 1
color = (153, 255, 205) # kolor tekstu (BGR)
thickness = 2
cv2.putText(img, text, position, font, font_scale, color, thickness)

cv2_imshow(img)
cv2.waitKey(0)

