# -*- coding: utf-8 -*-
"""Projekt_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Dk2uHwKC1m4n61yqgVcNj3qVRYdKw1G
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
import sklearn
import seaborn as sns
#import statistics as st
import csv
from scipy import stats

Dane = pd.read_csv("1953-2018.csv",skiprows=4)

Dane

Dane.columns = ['Data','Temperatura', 'Odchyłka']

f_c = lambda f:5/9*(f-32)

Dane['Temperatura'] = Dane['Temperatura'].apply(f_c)

Dane

Dane['Data'] = Dane['Data'].astype(str)

Dane['Data'] = Dane['Data'].apply(lambda x : x[0:4])

Dane

Dane['Data'] = Dane['Data'].astype(int)

Dane.describe()

linear_regression = stats.linregress(x=Dane.Data, y=Dane.Temperatura)

linear_regression.slope * 2022 + linear_regression.intercept



y = pd.DataFrame(Dane, columns=['Data','Temperatura'])
osie=y.plot(x='Data',y='Temperatura', style=".-")